#!/bin/sh

# Check for built files, and yell at user if not
# Full credit to Andy Ray: http://blog.andrewray.me/dealing-with-compiled-files-in-git/

# Find source files that are marked as modified
sources=`git status -s | grep 'M.*src\/.*'`

# Find built files that have changed (we don't use M because they could be deleted, etc)
built=`git status -s | grep 'dist\/.*'`

# If source files have changed, but not built files, block the commit
if [ -n "$sources" ] && [ -z "$built" ]; then
    echo "ERROR: You forgot to compile! You must compile before you can commit."
    exit 1
fi
# If source files and built files have changed, make sure the built files are in the index before committing
if [ -n "$sources" ] && [ -n "$built" ]; then
    git add dist
fi
